config/routes.rb
class WebDomainConstraint
  # Review Appsでは毎回ドメインが変更されるのでドメイン制約をつけない
  def self.matches?(request)
    ENV['REVIEW_APP'].present? || request.host == (ENV['WEB_DOMAIN'])
  end
end

class AdminDomainConstraint
  # Review Appsでは毎回ドメインが変更されるのでドメイン制約をつけない
  def self.matches?(request)
    ENV['REVIEW_APP'].present? || request.host == (ENV['ADMIN_DOMAIN'])
  end
end

Rails.application.routes.draw do
  require 'sidekiq/web'
  #
  # webサービス用のドメイン
  #
  constraints(WebDomainConstraint) do
    root to: 'welcome#index'
    devise_for :users, path: 'users', controllers: {
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      sessions: 'users/sessions'
    }
    resources :items
    namespace :users do
      resources :items
    end
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  #
  # 管理者のドメイン
  #
  constraints(AdminDomainConstraint) do
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: 'button',
        aria: { contorls: 'navbar', expanded: 'false' },
        data: { target: '#navbar', toggle: 'collapse' } }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to Settings.meta.site, root_path, class: 'navbar-brand'

    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to new_user_registration_path do
            &nbsp;
            = t('helpers.label.user.sign_up')
        %li
          = link_to new_user_session_path do
            &nbsp;
            = t('helpers.label.user.log_in')

app/views/application/_users_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: 'button',
        aria: { contorls: 'navbar', expanded: 'false' },
        data: { target: '#navbar', toggle: 'collapse' } }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to Settings.meta.site, root_path, class: 'navbar-brand'

    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to new_users_item_path do
            %i.fa.fa-bell
            &nbsp;
            = t('application.users_navbar.item')

        %li
          = link_to destroy_user_session_path, method: :delete do
            &nbsp;
            = t('helpers.label.user.log_out')